# Generated by Django 2.2.5 on 2019-09-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.CharField(max_length=300)),
                ('homeImage', models.FilePathField(path='/img')),
                ('description', models.TextField()),
            ],
        ),
    ]
